"""Build the Jamila widget's generated files from their sources:

    web/tokens.json          -> web/tokens.css
    web/assets/Icons/*.svg   -> the ICONS block in web/components/bundle.js

and check every text token against the grounds its note names (4.5:1, or the
token's own "min"), in both themes, plus the focus ring / halo pair on every
fill in "focus_fills" (one of the two must clear 3:1).

    python -m scripts.build_web            # write the generated files
    python -m scripts.build_web --check    # exit 1 if they are stale or a pair fails
"""

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Dict, List

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
TOKENS_JSON = WEB / "tokens.json"
TOKENS_CSS = WEB / "tokens.css"
ICON_DIR = WEB / "assets" / "Icons"
BUNDLE_JS = WEB / "components" / "bundle.js"

THEMES = ("light", "dark")
TEXT_MIN = 4.5
FOCUS_MIN = 3.0
ICONS_START = "/* <icons> generated by scripts/build_web.py from assets/Icons/*.svg */"
ICONS_END = "/* </icons> */"


# ---- contrast (WCAG 2.x relative luminance) ----

def _channel(c: float) -> float:
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def luminance(hex_color: str) -> float:
    h = hex_color.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    return 0.2126 * _channel(r) + 0.7152 * _channel(g) + 0.0722 * _channel(b)


def contrast(a: str, b: str) -> float:
    hi, lo = sorted((luminance(a), luminance(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def check_tokens(tokens: dict) -> List[str]:
    """Every failing pair, as a readable line. Empty means all pass."""
    colors = tokens["color"]
    errors = []
    for name, tok in colors.items():
        floor = tok.get("min", TEXT_MIN)
        for ground in tok.get("on", []):
            for theme in THEMES:
                ratio = contrast(tok[theme], colors[ground][theme])
                if ratio < floor:
                    errors.append(f"{theme}: {name} on {ground} is {ratio:.2f}:1, needs {floor}:1")
    for theme in THEMES:
        ring, halo = colors["focus"][theme], colors["focus-offset"][theme]
        for fill in tokens.get("focus_fills", []):
            base = colors[fill][theme]
            # The halo sits against the element; the ring sits against the halo.
            if max(contrast(halo, base), contrast(ring, halo)) < FOCUS_MIN:
                errors.append(f"{theme}: focus ring and halo both under {FOCUS_MIN}:1 on {fill}")
    return errors


# ---- tokens.css ----

def _px(v) -> str:
    return "0" if v == 0 else f"{v}px"


def _theme_vars(tokens: dict, theme: str) -> List[str]:
    lines = [f"  --j-{name}: {tok[theme]};" for name, tok in tokens["color"].items()]
    lines += [f"  --j-shadow-{name}: {tok[theme]};" for name, tok in tokens["shadow"].items()]
    return lines


def render_css(tokens: dict) -> str:
    fonts = {k: v["stack"] for k, v in tokens["font"].items()}
    static = [f"  --j-font-{k}: {v};" for k, v in fonts.items()]
    for name, t in tokens["type"].items():
        static.append(f"  --j-type-{name}: {t['weight']} {t['size']}px/{t['line']}px var(--j-font-{t['family']});")
    static += [f"  --j-space-{k}: {_px(v)};" for k, v in tokens["space"].items()]
    static += [f"  --j-radius-{k}: {_px(v)};" for k, v in tokens["radius"].items() if isinstance(v, (int, float))]
    static += [f"  --j-motion-{k}: {v};" for k, v in tokens["motion"].items()]
    static += [f"  --j-size-{k}: {_px(v)};" for k, v in tokens["size"].items()]
    light, dark = _theme_vars(tokens, "light"), _theme_vars(tokens, "dark")
    out = [
        "/* Generated from tokens.json by `python -m scripts.build_web`. Do not edit by hand. */",
        "",
        ":root, :host {",
        *static,
        *light,
        "}",
        "",
        '[data-j-theme="dark"] {',
        *dark,
        "}",
        "",
        "@media (prefers-color-scheme: dark) {",
        '  [data-j-theme="auto"] {',
        *("  " + line for line in dark),
        "  }",
        "}",
        "",
    ]
    return "\n".join(out)


# ---- icons ----

_SVG_INNER = re.compile(r"<svg\b[^>]*>(.*)</svg>", re.S)


def load_icons(icon_dir: Path = ICON_DIR) -> Dict[str, str]:
    icons = {}
    for path in sorted(icon_dir.glob("*.svg")):
        m = _SVG_INNER.search(path.read_text(encoding="utf-8"))
        if not m:
            raise ValueError(f"{path.name}: no <svg> element")
        icons[path.stem] = re.sub(r"\s+", " ", m.group(1)).strip()
    return icons


def render_icons_block(icons: Dict[str, str]) -> str:
    body = ",\n".join(f"    {json.dumps(name)}: {json.dumps(inner)}" for name, inner in icons.items())
    return f"{ICONS_START}\n  const ICONS = {{\n{body}\n  }};\n  {ICONS_END}"


def inject_icons(bundle: str, icons: Dict[str, str]) -> str:
    start, end = bundle.find(ICONS_START), bundle.find(ICONS_END)
    if start < 0 or end < 0:
        raise ValueError("bundle.js has no icons markers")
    return bundle[:start] + render_icons_block(icons) + bundle[end + len(ICONS_END):]


# ---- entry point ----

def build() -> Dict[Path, str]:
    """The generated files' expected contents."""
    tokens = json.loads(TOKENS_JSON.read_text(encoding="utf-8"))
    bundle = BUNDLE_JS.read_text(encoding="utf-8")
    return {TOKENS_CSS: render_css(tokens), BUNDLE_JS: inject_icons(bundle, load_icons())}


def stale_files() -> List[Path]:
    return [p for p, text in build().items() if not p.exists() or p.read_text(encoding="utf-8") != text]


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale or a pair fails")
    args = parser.parse_args(argv)

    errors = check_tokens(json.loads(TOKENS_JSON.read_text(encoding="utf-8")))
    for e in errors:
        print(f"contrast: {e}")
    if args.check:
        stale = stale_files()
        for p in stale:
            print(f"stale: {p.relative_to(ROOT)} (run: python -m scripts.build_web)")
        return 1 if errors or stale else 0
    for path, text in build().items():
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
